### ISSUE TITLE
http://bernardphp.com/docs/juno redirects to malware

### ISSUE THREAD

**Issue by thinkspill** [bernardphp/Juno#18]

**Comment by archon810** [comment]
http://bernardphp.com same thing. The whole site is a malware redirect now. Why did nobody resolve this yet?

**Comment by henrikbjorn** [comment]
I don't have the domain anymore.

**Comment by archon810** [comment]
But you do have the ability to change the links pointing to it from this very repo which have led people to malware for over a year. It's irresponsible to have left them up for so long knowing your domain is gone. 

This project's description: "Web Application for monitoring Bernard. - http://bernardphp.com/docs/juno"

**Comment by henrikbjorn** [comment]
> But you do have the ability to change the links pointing to it from this very repo which have led people to malware for over a year. It's irresponsible to have left them up for so long knowing your domain is gone.
> 
> This project's description: "Web Application for monitoring Bernard. - http://bernardphp.com/docs/juno"

I don't have access to the organisation anymore. I am not part of the project anymore.

 @sagikazarmark Can you fix it ?

**Comment by sagikazarmark** [comment]
Sure, thanks for the ping. Done.
